- PINCE.py
This is a really small change, but was causing some issues with the AUR package. The shebang needs to be on the first line or the program loader will just ignore it.
> Fixed typo with shebang.

- PINCE.py
- libPINCE/gdb_python_scripts/GDBCommandExtensions.py
- libPINCE/type_defs.py
This commit replaces the TraceInstructionsTree class with a tuple to simplify object serialization.
I have had success testing it on a few programs, but please inform me if any issues arise.
> Replace TraceInstructionsTree with a tuple.

- .travis.yml
- install.sh
It is not required to call the package manager multiple times. It is enough to call it once with all packages. Do that to reduce code duplication.
To support other distros which are not using `apt-get`, use `lsb_release -d -s` to get the distribution name from `/etc/os-release`. Then check if it contains "SUSE" and use `zypper` + the SUSE package names in this case. But still default to a Debian release.
> install.sh: Detect OS and add SUSE support

- PINCE.py
It's quite annoying that PINCE prints a `IndexError: list index out of range` error message every time `B` or `D` is pressed when nothing is selected.
> Handle error properly instead of raising index out of bound error

- PINCE.py
Original key press event should be called whenever no overload is found, otherwise some keyboard shortcuts (use Shift or Ctrl to select multiple rows) won't work.
I realize that I caused this bug. Sorry for that...
> Bugfix for tableWidget_AddressTable_keyPressEvent

- PINCE.py
- libPINCE/GDB_Engine.py
The 'create process' feature appears to be a bit broken.
```
[user202729@archlinux PINCE]$ gdb a
GNU gdb (GDB) 8.1
[...]
Reading symbols from a...(no debugging symbols found)...done.
(gdb) info file
Symbols from "/home/user202729/PINCE/a".
Local exec file:
`/home/user202729/PINCE/a', file type elf64-x86-64.
Entry point: 0x520
[...]
(gdb) starti
Starting program: /home/user202729/PINCE/a 
Program stopped.
0x00007ffff7dd8fb0 in _start () from /lib64/ld-linux-x86-64.so.2
(gdb) info file
Symbols from "/home/user202729/PINCE/a".
Native process:
Using the running image of child process 14714.
While running this, GDB does not access memory from...
Local exec file:
`/home/user202729/PINCE/a', file type elf64-x86-64.
Entry point: 0x555555554520
[...]
```
Before mapping the process to virtual …
> Fix create process

- GUI/SettingsDialog.py
- GUI/SettingsDialog.ui
- PINCE.py
Allows PINCE to automatically attach to process with matching names when it's started. Useful for testing (although the popup "memory viewer" window can be annoying).
Cheat Engine has a similar feature, but it:
* Doesn't allow regex
* Can attach at all time, not just startup
It's allowed to attach to `self_pid` using this method.
-------
There is a nested for loop break at line 350, which may looks a bit confusing.
> Auto attach

- GUI/CustomLabels/FlagRegisterLabel.py
- GUI/CustomLabels/RegisterLabel.py
Due to the color: black stylesheet that is used for when a register has not changed, the register texts are almost unreadable on dark themes after process attachment:
This fix allows the color property to be reset back to it's initial value, which would be white for dark themes and black for the white themes.
> Fixed hardcoded black text color for dark themes

- install_pince.sh
Added support for fedora by allowing `install_pince.sh` to use dnf to install dependencies, will not work before Fedora 22 due to a package manager change.
> Added Fedora support with dnf

- PINCE.sh
This might cause conflicts when installing PINCE via a package manager, as running the program as root just allows it to drop its bytecode files where it wants and the installation directory would therefore contain files that aren't in the original package, causing warnings or even errors in the process.
Disabling writing bytecode to files might also keep users from having undeletable files in their home directory.
> Don't write Python bytecode

- install_gdb.sh
- install_pince.sh
Also removed unnecessary grepping for how many cores are available. `make -j` automatically uses the maximum amount if none are specified.
> Fix shellcheck issues on install scripts

- install_pince.sh
Small PR
Trying to solve the "Always Showing Successful installation" issue. 
- Add Exit on Error Function
- also inofficially added SteamOS to the Switch Case 
Locally Tested with Xubuntu 20.04 with Python 3.10 in a successful run and in multiple artificially failing runs. 
(Thats my first Public PR, so i'm not sure if its correct or not. Feedback appreciated) 
Bastian
> Feature exit install script on error

- PINCE.py
To do an initial scan, I have to press the `First Scan` twice in order to have 
matches in the matches table, this seems to hapen because of wrong 
`self.scan_mode` value in `MainForm`
Initially `self.scan_mode` is `type_defs.SCAN_MODE.ONGOING`
shouldn't it be `self.scan_mode` be `type_defs.SCAN_MODE.NEW` ?
> BUGFIX having to press `First Scan` twice in initial scan

- install_pince.sh
Needed for Debian based distros that do not come with Python 3 headers by default.
> Add Python 3 dev headers for APT distros

- .gitignore
- PINCE.sh
- README.md
- install_pince.sh
- libpince/GDB_Engine.py
- libpince/gdbinit_venv
PINCE installer should now create a ".venv/PINCE" folder that will contain the virtual environment that PINCE will now run in.
> Change PINCE installation to use Python venv

- PINCE.sh
- install_pince.sh
This is so users cannot run PINCE.sh as sudo themselves, which would break venv.
> Add check for user initiated sudo

- PINCE.py
fixes and closes #161 
not sure if the code quality is as you want it. 
If the flashing is too fast, you can reduce the timer to ~500 ms, or whatever you see fit. 
Automatically restores normal behavior if process is attached, as well as readding indicator if inferior gdb attached process is closed or dies.
> add Indicator for no Process

- install_gdb.sh
- install_pince.sh
My laptop (16 CPU threads, 64GB memory) went Out-Of-Memory while compiling GDB. I think the culprit here is `-j`. I saw from `man make`:
```
If the -j option is given without an argument, make will not limit the number of jobs that can run simultaneously.
```
I tested running the script again after a fresh reboot and the same thing happened again.
> Limit make jobs to 4 to prevent OOM

- install_pince.sh
These commits remove misc.py completely and any GTK dependency needed from scanmem-PINCE fork.
> Scanmem changes

- .gitmodules
- PINCE.py
- install_pince.sh
scanmem-PINCE was renamed to libscanmem-PINCE due to it now being fully converted to a backend library.
Anything that wasn't libscanmem was stripped and following main changes made:
- PTRACE functions were removed. libscanmem-PINCE now relies on proc maps and mem files. OS without these files will fail during `./configure` stage.
- All non back-end messaging was deleted. Same as having `set_backend()` in `scanmem.py`'s `__init__`.
PINCE wise:
-  Intltool dependency removed. This was used by GameConqueror, scanmem's GUI, to handle PO translation files.
- Readline dependency removed. This was needed by scanmem CLI program, which was included in the compilation. Since now the CLI program is removed and we're only compiling the library, it's not needed anymore.
- `noptrace` option setting …
> Scanmem overhaul

- PINCE.py
This PR moves the following commands from text input based to direct function calls:
- undo
- redo
- pid
- reset
This is a part of a long term plan to convert all of libscanmem's commands to their own proper functions instead of relying on sending text input.
Libscanmem recompilation will be needed.
> Partial libscanmem library function conversion

- .vimspector.json
Vimspector broke after we did preserve-env=PATH fixes for Debian/Ubuntu
> Fix vimspector missing modules issue

- PINCE.py
- libpince/typedefs.py
QoL: click outside freeze checkbox to change freeze type
BugFix: Reapply Styling when freeze gets enabled as freeze type is saved but the type indicator in UI is reset
QoL: Autoselect Process with Enter if only one Process is found
QoL: Press Enter in lineEdit_Scan for Search
QoL: Add CTRL+Enter/Return for "New Search"
> QoL Changes

- PINCE.py
This pull request adds key press event handling for deleting rows in the valuesearchtable. 
It allows users to delete selected rows by pressing the Delete key.
currently using scanmem.send_command() - possible rewrite to custom method in wrapper class ?
> FEAT add key handler to remove search results

- PINCE.py
- libpince/debugcore.py
- libpince/typedefs.py
Part 1 of a two-parter feature which includes changes to the backend of read_pointer function where we store the results of each pointer+offset combo dereference and give them to the UI to reduce pointer features confusion.
Part 2 will include the UI changes.
Two new types were introduced in this PR:
- **PointerChainRequest**: This is the previous PointerType class with added typehints and revised description/documentation. This is the type that will be supplied to read_pointer_chain (previously named read_pointer) function
- **PointerChainResult**: This is a new type that will be returned by read_pointer_chain. It has a list[int] instance variable that includes the result of each dereference done inside read_pointer_chain. It includes 2 helper functions for retrieving the last address …
> Read_Pointer backend changes

- PINCE.py
- libpince/debugcore.py
This change will show where the pointer chain breaks right in the UI instead of replacing all entries with ?? if a single read is invalid.
> Change read_pointer_chain to add 0 for invalid offset reads

- PINCE.py
while scanning, you can cause a segmentation fault if you use use a nextscan hotkey while already scanning, this pr should fix that by adding a boolean flag `self.is_scanning` that is checked before scanning in `nextscan_hotkey_pressed`
> fix SIGSEGV when using `nextscan_hotkey_pressed` while already scanning
